// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebApplication10;

#nullable disable

namespace WebApplication10.Migrations
{
    [DbContext(typeof(TradingDbContext))]
    partial class TradingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WebApplication10.Models.ClientModels.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PortfolioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Евгений",
                            LastName = "Морозов",
                            Password = "1234",
                            PortfolioId = 1
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "Владимир",
                            LastName = "Сапронов",
                            Password = "1234",
                            PortfolioId = 2
                        });
                });

            modelBuilder.Entity("WebApplication10.Models.PortfolioModels.Portfolio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Cash")
                        .HasColumnType("integer");

                    b.Property<int>("ClientId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ClientId")
                        .IsUnique();

                    b.ToTable("Portfolios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cash = 15000,
                            ClientId = 0
                        },
                        new
                        {
                            Id = 2,
                            Cash = 20000,
                            ClientId = 0
                        });
                });

            modelBuilder.Entity("WebApplication10.Models.PortfolioStockModels.PortfolioStock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Count")
                        .HasColumnType("integer");

                    b.Property<int>("PortfolioId")
                        .HasColumnType("integer");

                    b.Property<int>("StockId")
                        .HasColumnType("integer");

                    b.Property<int>("TotalPrice")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PortfolioId");

                    b.HasIndex("StockId");

                    b.ToTable("PortfoliosStocks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Count = 5,
                            PortfolioId = 1,
                            StockId = 1,
                            TotalPrice = 30000
                        },
                        new
                        {
                            Id = 2,
                            Count = 8,
                            PortfolioId = 2,
                            StockId = 2,
                            TotalPrice = 24000
                        },
                        new
                        {
                            Id = 3,
                            Count = 12,
                            PortfolioId = 2,
                            StockId = 1,
                            TotalPrice = 72000
                        });
                });

            modelBuilder.Entity("WebApplication10.Models.StockModels.Stock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Price")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Stocks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Lukoil",
                            Price = 6000
                        },
                        new
                        {
                            Id = 2,
                            Name = "Yandex",
                            Price = 3000
                        });
                });

            modelBuilder.Entity("WebApplication10.Models.PortfolioModels.Portfolio", b =>
                {
                    b.HasOne("WebApplication10.Models.ClientModels.Client", "Client")
                        .WithOne("Portfolio")
                        .HasForeignKey("WebApplication10.Models.PortfolioModels.Portfolio", "ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("WebApplication10.Models.PortfolioStockModels.PortfolioStock", b =>
                {
                    b.HasOne("WebApplication10.Models.PortfolioModels.Portfolio", "Portfolio")
                        .WithMany("PortfolioStocks")
                        .HasForeignKey("PortfolioId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.HasOne("WebApplication10.Models.StockModels.Stock", "Stock")
                        .WithMany("PortfoliosStock")
                        .HasForeignKey("StockId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.Navigation("Portfolio");

                    b.Navigation("Stock");
                });

            modelBuilder.Entity("WebApplication10.Models.ClientModels.Client", b =>
                {
                    b.Navigation("Portfolio");
                });

            modelBuilder.Entity("WebApplication10.Models.PortfolioModels.Portfolio", b =>
                {
                    b.Navigation("PortfolioStocks");
                });

            modelBuilder.Entity("WebApplication10.Models.StockModels.Stock", b =>
                {
                    b.Navigation("PortfoliosStock");
                });
#pragma warning restore 612, 618
        }
    }
}
